name: Pre-Commit

on:
  workflow_call:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v6

      - name: Pull pre-commit Docker image
        run: docker pull ghcr.io/antonbabenko/pre-commit-terraform:latest

      - name: Run pre-commit hooks
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/lint" \
            -w /lint \
            --entrypoint /bin/sh \
            ghcr.io/antonbabenko/pre-commit-terraform:latest \
            -c "tflint --init && pre-commit run -a"